title: Brian Honea
#logo: fill in file path later
description: I am pursuing a career in Data Science and Machine Learning. I am still learning how to code and will upload projects here!
show_downloads: true
theme: jekyll-theme-minimal
